name: linearity
description: "An application with educational functions in the field of mathematics."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0

  # Firebase dependencies
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7

  image_picker: ^1.1.2  
  flutter_local_notifications: ^19.2.1
  firebase_storage: ^12.4.5
  permission_handler: ^12.0.0
  timezone: ^0.10.1
  cached_network_image: ^3.4.1

  shared_preferences: ^2.0.15

  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/icons/avatar_1.svg
    - lib/assets/icons/avatar_2.svg
    - lib/assets/icons/avatar_3.svg
    - lib/assets/icons/avatar_4.svg
    - lib/assets/icons/avatar_5.svg
    - lib/assets/icons/avatar_6.svg
    - lib/assets/icons/avatar_7.svg
    - lib/assets/icons/avatar_8.svg
    - lib/assets/icons/avatar_9.svg
    - lib/assets/icons/avatar_f2.svg
    - lib/assets/icons/arrow_left.svg
    - lib/assets/icons/arrow_right_simple.svg
    - lib/assets/icons/coin.svg
    - lib/assets/icons/fire.svg
    - lib/assets/icons/fire_dark.svg
    - lib/assets/icons/fire_test.svg
    - lib/assets/icons/blue_flame.svg
    - lib/assets/icons/hint.svg
    - lib/assets/icons/home.svg
    - lib/assets/icons/matrix_simple.svg
    - lib/assets/icons/matrix_medium.svg
    - lib/assets/icons/matrix_hard.svg
    - lib/assets/icons/medal.svg
    - lib/assets/icons/line_medal.svg
    - lib/assets/icons/profile.svg
    - lib/assets/icons/setting.svg
    - lib/assets/icons/tick-circle.svg
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: lib/assets/fonts/IBMPlexSans-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/IBMPlexSans-Italic.ttf
          style: italic
